AccountID: "963662274920"
App: "HalappNotification"
Environment: DEVELOPMENT
Region: eu-central-1
# SNS
ORDER_SNSOrderTopic: "ORDER_OrderTopic"
# S3
S3OrderCreatedEmailTemplate: "halapp-order-created.ejs"
S3OrderCanceledEmailTemplate: "halapp-order-canceled.ejs"
S3OrderDeliveredEmailTemplate: "halapp-order-delivered.ejs"
# SES
SESFromEmail: no-reply@halapp.io
SESCCEmail: furkan.ozdeslik@gmail.com
# LAMBDA
LAMBDAAccountGetOrganizationHandler: "Account-GetOrganizationHandler"
LAMBDAListingGetInventoriesHandler: "Listing-GetInventoriesHandler"

