AccountID: "751021557844"
App: "HalappNotification"
Environment: PRODUCTION
Region: eu-central-1
# SNS
ORDER_SNSOrderTopic: "ORDER_OrderTopic"
# S3
S3OrderCreatedEmailTemplate: "halapp-order-created.ejs"
S3OrderCanceledEmailTemplate: "halapp-order-canceled.ejs"
S3OrderDeliveredEmailTemplate: "halapp-order-delivered.ejs"
# SES
SESFromEmail: no-reply@halapp.io
SESCCEmail: info@halapp.io
#LAMBDA
LAMBDAAccountGetOrganizationHandler: "Account-GetOrganizationHandler"
LAMBDAListingGetInventoriesHandler: "Listing-GetInventoriesHandler"


