AccountID: "751021557844"
App: "HalappNotification"
Environment: PRODUCTION
Region: eu-central-1
# SNS
ORDER_SNSOrderCreatedTopic: "ORDER_OrderCreatedTopic"
# S3
S3OrderCreatedEmailTemplate: "order-created.ejs"
# SES
SESFromEmail: no-reply@halapp.io
SESCCEmail: info@halapp.io
#LAMBDA
LAMBDAAccountGetOrganizationHandler: "AccountGetOrganizationHandler"
LAMBDAListingGetInventoriesHandler: "ListingGetInventoriesHandler"


